# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DqhX-pJdiTzHucb8IwJ0HoZZLcAGKUKP
"""

print("app.py importing...")
from flask import Flask, request
from PIL import Image
import io

from cancer_model import predict

app = Flask(name)

@app.route("/", methods=["GET"])
def index():
    return """
<!DOCTYPE html>
<html>
<head>
  <title>Cancer Classifier</title>
</head>
<body>
  <h1>Cancer Classifier</h1>
  <h2>Cancer Image Classifier</h2>

  <form action="/predict" method="post" enctype="multipart/form-data">
    <p>Select an image:</p>
    <input type="file" name="image" accept="image/*" required>
    <br><br>
    <button type="submit">Upload and Classify</button>
  </form>
</body>
</html>
"""


@app.route("/predict", methods=["POST"])
def predict_route():
    file = request.files.get("image")
    if file is None or file.filename == "":
        return "No file selected", 400

    try:
        contents = file.read()
        image = Image.open(io.BytesIO(contents))

        class_name, probs = predict(image)

        # Sort probs descending for display
        sorted_probs = sorted(probs.items(), key=lambda x: x[1], reverse=True)

        # Build HTML result page
        html = []
        html.append("<h1>Prediction Result</h1>")
        html.append(f"<h2>Top prediction: {class_name}</h2>")

        html.append("<h3>All subclass probabilities</h3>")
        html.append("<ul>")
        for cls, p in sorted_probs:
            html.append(f"<li>{cls}: {p:.4f}</li>")
        html.append("</ul>")

        html.append('<p><a href="/">Back</a></p>')

        return "\n".join(html)
    except Exception as e:
        return f"Error: {e}", 500


if name == "main":
    app.run(debug=True)