# -*- coding: utf-8 -*-
"""cancer_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v8qooI_wkJnjK9UzXLIckUBl9king_98
"""

import json
from pathlib import Path

import torch
from torch import nn
from torchvision import transforms
from torchvision.models import resnet50, ResNet50_Weights
from PIL import Image


BASE_DIR = Path(file).resolve().parent


WEIGHTS_PATH = BASE_DIR / "best_model_epoch5.pt"
CLASSES_PATH = BASE_DIR / "classes.json"


with open(CLASSES_PATH, "r") as f:
    CLASS_NAMES = json.load(f)


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")


def load_model():

    model = resnet50(weights=ResNet50_Weights.DEFAULT)
    model.fc = nn.Linear(model.fc.in_features, 26)


    state_dict = torch.load(WEIGHTS_PATH, map_location=DEVICE)
    model.load_state_dict(state_dict)

    model.to(DEVICE)
    model.eval()
    return model



MODEL = load_model()


EVAL_TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])


@torch.no_grad()
def predict(image: Image.Image):
    # Ensure 3-channel RGB
    if image.mode != "RGB":
        image = image.convert("RGB")

    # Preprocess and move to device
    tensor = EVAL_TRANSFORM(image).unsqueeze(0).to(DEVICE)

    # Forward pass
    logits = MODEL(tensor)
    probs = torch.softmax(logits, dim=1)[0]

    # Top-1 prediction
    pred_idx = int(torch.argmax(probs).item())
    pred_class = CLASS_NAMES[pred_idx]

    # Full probability map
    probs_dict = {
        CLASS_NAMES[i]: float(probs[i].item())
        for i in range(len(CLASS_NAMES))
    }

    return pred_class, probs_dict